# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Xue "Shirley" Wu
title: Web Application Developer
email: xwu33@crimson.ua.edu
website: https://xwu33.github.io/

# Social links
twitter_username: Shirley03927086
github_username:  xwu33
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: xueshirle
linkedin_username: xue-shirley-wu-568b5713b
# pinterest_username: jekyll
youtube_username: Xue "Shirley" Wu
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Shirley and I'm a web application developer in Office of Education Technology at the University of Alabama. As well as graduate assistant at office of library technology before I graduate. I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>PHP</mark> and <mark>JAVA</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Skiing
   - Reading
   - Singing
   - [Being a Judge at 2017 and 2018 Alabama Robotics Competition](http://outreach.cs.ua.edu/robotics-contest/2017.html and http://outreach.cs.ua.edu/robotics-contest/2018.html)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
